version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db01
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local
