# Generated by Django 5.0.1 on 2024-01-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='price',
        ),
    ]
